name: "GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  mkdocs:
    if: github.repository == 'GideokKim/google-python-style-guide-kr'  # upstream 저장소 확인
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64

      - name: "Run pip install"
        run: >
          python3 -m pip install -r requirements.txt
      - name: "Run MkDocs(build)"
        run: >
          python3 -m mkdocs build --site-dir _site

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - uses: actions/deploy-pages@v4